package mysort;

import java.awt.EventQueue;
import javax.swing.JFrame;

public class AlgorithmAnimation {
	public static void main(String[] args) {
		EventQueue.invokeLater(new Runnable() {
			public void run() {
				JFrame frame = new AnimationFrame("BubbleSort-Bar-Vertical");
				frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
				frame.setVisible(true);
				JFrame frame1 = new AnimationFrame("QuickSort-Bar-Vertical");
				frame1.setLocation(0, 195);
				frame1.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
				frame1.setVisible(true);
				JFrame frame1a = new AnimationFrame("InsertSort-Bar-Vertical");
				frame1a.setLocation(0, 390);
				frame1a.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
				frame1a.setVisible(true);
				JFrame frame1ab = new AnimationFrame("MergeSort-Bar-Vertical");
				frame1ab.setLocation(0, 585);
				frame1ab.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
				frame1ab.setVisible(true);
				JFrame frame2 = new AnimationFrame("QuickSortBarHorz");
				frame2.setLocation(190, 195);
				frame2.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
				frame2.setVisible(true);
				JFrame frame3 = new AnimationFrame("BubbleSortBarHoriz");
				frame3.setLocation(190, 0);
				frame3.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
				frame3.setVisible(true);
				JFrame frame3a = new AnimationFrame("InsertSortBarHoriz");
				frame3a.setLocation(190, 390);
				frame3a.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
				frame3a.setVisible(true);
				JFrame frame3ab = new AnimationFrame("MergeSortBarHoriz");
				frame3ab.setLocation(190, 585);
				frame3ab.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
				frame3ab.setVisible(true);
				JFrame frame4 = new AnimationFrame("BubbleSort-Line-Vertical");
				frame4.setLocation(360, 0);
				frame4.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
				frame4.setVisible(true);
				JFrame frame5 = new AnimationFrame("QuickSort-Line-Vertical");
				frame5.setLocation(360, 195);
				frame5.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
				frame5.setVisible(true);
				JFrame frame5a = new AnimationFrame("InsertSort-Line-Vertical");
				frame5a.setLocation(360, 390);
				frame5a.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
				frame5a.setVisible(true);
				JFrame frame5ab = new AnimationFrame("MergeSort-Line-Vertical");
				frame5ab.setLocation(360, 585);
				frame5ab.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
				frame5ab.setVisible(true);
				JFrame frame6 = new AnimationFrame("BubbleSort-Line-Horizontal");
				frame6.setLocation(530, 0);
				frame6.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
				frame6.setVisible(true);
				JFrame frame7 = new AnimationFrame("QuickSort-Line-Horizontal");
				frame7.setLocation(530, 195);
				frame7.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
				frame7.setVisible(true);
				JFrame frame7a = new AnimationFrame("InsertSort-Line-Horizontal");
				frame7a.setLocation(530, 390);
				frame7a.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
				frame7a.setVisible(true);
				JFrame frame7ab = new AnimationFrame("MergeSort-Line-Horizontal");
				frame7ab.setLocation(530, 585);
				frame7ab.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
				frame7ab.setVisible(true);
				JFrame frame8 = new AnimationFrame("BubbleSort-Cir-Horizontal");
				frame8.setLocation(700, 0);
				frame8.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
				frame8.setVisible(true);
				JFrame frame9 = new AnimationFrame("QuickSort-Cir-Horizontal");
				frame9.setLocation(700, 195);
				frame9.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
				frame9.setVisible(true);
				JFrame frame9a = new AnimationFrame("InsertSort-Cir-Horizontal");
				frame9a.setLocation(700, 390);
				frame9a.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
				frame9a.setVisible(true);
				JFrame frame9ab = new AnimationFrame("MergeSort-Cir-Horizontal");
				frame9ab.setLocation(700, 585);
				frame9ab.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
				frame9ab.setVisible(true);
				JFrame frame10 = new AnimationFrame("BubbleSort-Cir-Vertical");
				frame10.setLocation(870, 0);
				frame10.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
				frame10.setVisible(true);
				JFrame frame11 = new AnimationFrame("QuickSort-Cir-Vertical");
				frame11.setLocation(870, 195);
				frame11.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
				frame11.setVisible(true);
				JFrame frame11a = new AnimationFrame("InsertSort-Cir-Vertical");
				frame11a.setLocation(870, 390);
				frame11a.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
				frame11a.setVisible(true);
				JFrame frame11ab = new AnimationFrame("MergeSort-Cir-Vertical");
				frame11ab.setLocation(870, 585);
				frame11ab.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
				frame11ab.setVisible(true);
				JFrame frame12 = new AnimationFrame("BubbleSort-Dot");
				frame12.setLocation(1040, 0);
				frame12.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
				frame12.setVisible(true);
				JFrame frame13 = new AnimationFrame("QuickSort-Dot");
				frame13.setLocation(1040, 195);
				frame13.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
				frame13.setVisible(true);
				JFrame frame13a = new AnimationFrame("InsertSort-Dot");
				frame13a.setLocation(1040, 390);
				frame13a.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
				frame13a.setVisible(true);
				JFrame frame13ab = new AnimationFrame("MergeSort-Dot");
				frame13ab.setLocation(1040, 585);
				frame13ab.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
				frame13ab.setVisible(true);
				
			}
		});
	}
}
